### ISSUE TITLE
eyo --version не работает

### ISSUE THREAD

**Issue by mkpankov** [hcodes/eyo#10]
```
mkpankov@ubuntu:~$ eyo --version
module.js:327
    throw err;
    ^

Error: Cannot find module 'exit'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (/usr/lib/node_modules/eyo/bin/cli.js:7:14)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)
```

**Comment by hcodes** [comment]
Спасибо, поправил.
Теперь точно всё работает.
v3.0.1

![eyo](https://cloud.githubusercontent.com/assets/157520/18701519/c381ff18-7fe5-11e6-8155-002774e54b70.png)
